//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OUBus
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenDi
    {
        public ChuyenDi()
        {
            this.VeXes = new HashSet<VeXe>();
        }
    
        public int MaChuyenDi { get; set; }
        public Nullable<int> MaXe { get; set; }
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKhoiHanh { get; set; }
        public string DiemKhoiHanh { get; set; }
        public string DiemKetThuc { get; set; }
        public Nullable<int> SoGheTrong { get; set; }
        public Nullable<int> SoGheDat { get; set; }
        public Nullable<int> GiaVe { get; set; }
    
        public virtual BaoCaoDoanhThuChuyenDi BaoCaoDoanhThuChuyenDi { get; set; }
        public virtual XeKhach XeKhach { get; set; }
        public virtual ICollection<VeXe> VeXes { get; set; }
    }
}
