//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OUBus
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeKhach
    {
        public XeKhach()
        {
            this.ChuyenDis = new HashSet<ChuyenDi>();
        }
    
        public int MaXe { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public string BienSoXe { get; set; }
        public Nullable<int> SoGhe { get; set; }
    
        public virtual ICollection<ChuyenDi> ChuyenDis { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
